<?php

/**
 * @file
 * Contains donation_field.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function donation_field_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the donation module.
    case 'help.page.donation_field':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Donation Field') . '</p>';
      return $output;

    default:
  }
}

